### PR TITLE
Say yes in scala

### PR DESCRIPTION
**Pull request by annp89**
:)

### CODE REVIEW

**Comment by whoshuu** [comment]
Thanks for the PR @annp89! Be sure your program can handle pipes a la:

``` bash
scala yes 12345 | head -10 > output
```

The following should be helpful:

``` scala
import sun.misc.Signal
import sun.misc.SignalHandler

// Somewhere in main

val signal = new Signal("PIPE");
val handler = new SignalHandler {
    def handle(signal: Signal): Unit = {
        sys.exit(128 + signal.getNumber);
    }
};

Signal.handle(signal, handler);
```

**Comment by annp89** [comment]
Ah, right! ^ :+1:

**Comment by annp89** [comment]
Hmm..Trying to understand this more. What is the significance of `128 + signal.getNumber` ? Do we know the signal number for 'PIPE' ? Seems like we do, and if so, why cant we exit for the actual signal number that corresponds to 'PIPE'.

**Comment by whoshuu** [comment]
`SIGPIPE`'s number is `13`, so we could just use `141`. Using `128 + signal.getNumber` seems to be the right convention: http://tldp.org/LDP/abs/html/exitcodes.html.

Practically, it doesn't matter what you exit with, as long as you exit. Not exiting means that when the process gets a `SIGPIPE`, it just hangs.

**Comment by annp89** [comment]
:+1: Thanks for link! Makes sense.

**Comment by whoshuu** [comment]
@annp89, update on this PR?

**Comment by annp89** [comment]
Ugh, I didnt get time to look at this. Feel free to push the changes you recommeded as you see fit!

**Pull request merged**
